### ISSUE TITLE
Native Ads support

### ISSUE THREAD

**Issue by SquirrelMobile** [1dir1/admobrewarded#1]
Hello, thanks for your module @1dir1 ! Can you add support for Native Ads, Native Ads Express and Native Ads Advanced please ? Here is the documentation : https://developers.google.com/admob/android/native, https://developers.google.com/admob/android/native-express and https://developers.google.com/admob/android/native-advanced

**Comment by canbican** [comment]
I would love to, but it's beyond the scope of my current project. I hope there will be another customer asking for it :)

**Comment by SquirrelMobile** [comment]
@canbican maybe i can be that customer :-) Can you tell me how much it's cost to add this support please ? You can contact me at : thomas@squirrel.fr. Thanks !
